### PR TITLE
Use standard magento config approach

### PR DESCRIPTION
**Pull request by scottsb**
Use standard Magento configuration interfaces (both in a UI and OOP sense).

Also fixes these bugs:

- Argument order confusion in old configuration getter between `$scope` and `$scopeid` (actually worked, but only because MySQL was casting "default" to 0 on both sides of comparison in both where clauses, and `0 == 0`)
- PHP error when handling exceptions in immediate cron execution command.

Also cleans up inconsistent indention in files I was otherwise touching.

### CODE REVIEW

**Comment by gnuzealot** [comment]
This will have to be reviewed further, there were compatibility issues in magento versions using the standard approach which is why separate functions were made.

**Comment by gnuzealot** [comment]
I don't recall what versions, but I think it was in 2.0. I'll have to run it through testing and see.

**Comment by scottsb** [comment]
Magento 2.0 is past end of life. Do you still intend to support it with this extension?

**Comment by scottsb** [comment]
@gnuzealot I see you closed this without comment, which is obviously your prerogative, but I would appreciate some feedback as to why you didn't want to accept it?

**Pull request closed without merging**
