### PR TITLE
Fix undefined index error

### PR DESCRIPTION
**Pull request by oroskodias**
Fixes issue #30

### CODE REVIEW

**Comment by JesKingDev** [comment]
@oroskodias and @gnuzealot - Do you guys have any idea when this will be released? I have a Magento implementation affected by this and am eagerly awaiting a new release that includes this PR.

**Comment by ericvhileman** [comment]
@JesKingDev it was merged into master 13 days ago.

**Comment by JesKingDev** [comment]
@ericvhileman - Yes, but using the composer method of installation, there should be a release tag on the repo. The code is in master, but there hasn't been a release tagged that includes the changes.

**Comment by ericvhileman** [comment]
@gnuzealot can you please tag this release and tag all future releases.

**Comment by ericvhileman** [comment]
@JesKingDev the release has been tagged.

**Pull request merged**
